### ISSUE TITLE
How does this compare to draco?

### ISSUE THREAD

**Issue by jansol** [FractalFir/tmf#2]
[Draco](https://google.github.io/draco/) is a mesh data compression scheme that is supported e.g. in glTF ([with an extension](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_draco_mesh_compression) that e.g. [Blender supports out of the box](https://docs.blender.org/manual/en/3.3/addons/import_export/scene_gltf2.html#compression)) or as a standalone mesh format.

The README shows some comparisons against zipping up some common 3D formats, but based on the description the impression I got was that glb+draco would be a much closer alternative than a zipped fbx so that would be interesting to see. 

Draco is not the smallest library so it might also be interesting to take a look at the code size & runtime speed of the different solutions.

EDIT: another similar library is [meshoptimizer](https://github.com/zeux/meshoptimizer) which, while the main focus seems to be on optimizing meshes for more efficient rendering, also does some tricks to reduce file size.

**Comment by FractalFir** [comment]
Previously, I did not know about Draco, so this is why I did not test it. In terms of raw file size reduction, Draco on max compression and default settings wipes the floor with my project, compressing the mesh to just 22 kB. I do not know if I did something wrong while using Draco, because there are a couple of visible artifacts in blender.
![Screenshot from 2023-02-24 13-45-01](https://user-images.githubusercontent.com/75212430/221182164-14631ca1-a400-4395-b26a-f727d203f5ba.png)
Those artifacts persisted no mater the compression level, and when -preserve_polygons was enabled. 
Since I do not have almost any experience with Draco, this may be me just messing something up.
Additionally, Draco encode/decode speeds are noticeably higher (export 10-16ms and import 7-10 ms). 
In terms of LOC, my library is 3191 lines long, Draco is 74513 lines long, including documentation. The size of compiled release binary is 1 MB, while Draco is 4 MB. 
Comparisons to Draco are certainly a nice thing to have, but I need to double-check if those artifacts in Draco come from its compression or from my error.

**Comment by jansol** [comment]
Thanks! Those are great data points.

I have had to fit binaries in small ROMs lately, with the option of loading data from a much larger separate memory at runtime (albeit not 3D models at the moment) so I have a fresh appreciation for small code size.

Those artifacts should definitely not be there. I don't have any good guess as to what is happening either, though. The blender exporter does not really have *that* many options that one can screw up. It looks like e a discontinuity in normals so maybe draco is doing some meshlet optimization and has a bug with keeping normals smooth across meshlet boundaries.

**Comment by FractalFir** [comment]
I did not use the blender Draco exporter, I used Draco CLI. My blender install has some issues, so I wanted to ensure there are no problems/overhead coming from blender itself.
 It seems like the decoded file in .ply format has some vertices doubled and separate for faces, and a weld modifier in blender after the import fixes the issue. Additionally, decoding into other formats(.obj) and importing them seems to work just fine.

**Comment by FractalFir** [comment]
I have made a draft of a comparison to Draco in this [commit](https://github.com/FractalFir/tmf/commit/bb82be77720d624159083c591bf8792b36047cb8). I still need to make sure it is objective and 100% accurate (as an author of this project, I may be not as objective as I would like), but it seems pretty fair to me.

**Comment by jansol** [comment]
Looks good! And quite straightforward to expand to cover meshoptimizer too.
