### ISSUE TITLE
Add size comparisons with GLTF

### ISSUE THREAD

**Issue by sokorototo** [FractalFir/tmf#4]
**Is your feature request related to a problem? Please describe.**
GTLF is gaining massive traction as a reliable royalty-free general purpose scene description format. Consider adding comparisons to a model only gltf.

**Describe the solution you'd like**
Just as OBJ and Draco have sections in the readme, so should GLTF.

**Describe alternatives you've considered**
N/A

**Additional context**
It would;d be nice to compare tmf to GLTF, as more and more models are being distributed in it. Also a GLTF->TMF converter would be nice

**Comment by FractalFir** [comment]
I have added comparisons to both gltf and glb. 
As for the converter, it is entirely possible to implement it. The API is designed to allow for ease of creating importers/exporters, and the current .obj importer is using only the public API. The idea I have for importers is for them to be separate modules enabled by feature flags. The only reason .obj importer is not enabled/disabled by a feature flag is because it was needed for testing. I am currently working on a complete rewrite of the .obj importer to adhere to this rule.
Additionally, this rewrite brings small API changes that should make creating such an importer even easier. 
Sadly, importers for other projects are not something I can work on ATM because of time constraints.
But if anyone wants to implement an importer for any format, I would have no problem merging it into the project under a separate feature.

**Comment by sokorototo** [comment]
Importers for other formats are not your responsibility, thanks for the good work! Your only responsibility is to maintain this well! I'll write a bevy plugin for this when I get the time or even contribute
